name: Build "venus"

on:
  workflow_dispatch:

jobs:
  start_building:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt build-dep mesa -y

    - name: Execute build script
      run: bash ./venus_builder.sh

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: Venus magisk module 
        tag_name: github_run
        name: Nightly Action Release
        files: |
           workdir/vulkan-virtio.zip
